# Generated by Django 2.0 on 2018-02-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('NC', models.CharField(max_length=15)),
                ('serial', models.CharField(max_length=40)),
                ('addition_date', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
                ('tool_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_issues', to='cockpit.Tool')),
            ],
        ),
    ]
