# Generated by Django 2.0 on 2018-02-13 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('finish_date_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('actual_duration', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('b_factor', models.DecimalField(decimal_places=1, default=1.2, max_digits=4)),
                ('actual_b_factor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('service_order', models.CharField(blank=True, max_length=10, null=True)),
                ('ok_to_run', models.NullBooleanField(default=False)),
                ('status', models.CharField(blank=True, default='draft', max_length=30, null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=4)),
                ('vacation_hours', models.DecimalField(decimal_places=2, default=195, max_digits=5)),
                ('sap', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=50)),
                ('sup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss', to='cockpit.Engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('service_order', models.CharField(blank=True, max_length=10, null=True)),
                ('high_priority', models.NullBooleanField(default=False)),
                ('status', models.CharField(blank=True, default='todo', max_length=30, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Engineer')),
                ('owner', models.ManyToManyField(related_name='ownedtasks', to='cockpit.Engineer')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('customer_name', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('body_type', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.ToolOwner'),
        ),
        migrations.AddField(
            model_name='knownissue',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_known_issues', to='cockpit.Tool'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Shift'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_action_plans', to='cockpit.Engineer'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_plans', to='cockpit.Engineer'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='executer',
            field=models.ManyToManyField(blank=True, related_name='executed_action_plans', to='cockpit.Engineer'),
        ),
    ]
