# Generated by Django 2.0 on 2018-05-26 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='associated_cois', to='logistics.Material'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='reviewer_1st_line',
            field=models.ManyToManyField(blank=True, related_name='reviewed_action_plans_1st', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='reviewer_2nd_line',
            field=models.ManyToManyField(blank=True, related_name='reviewed_action_plans_2nd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_action_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_action_plans', to='cockpit.Tool'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Shift'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
