# Generated by Django 2.0 on 2018-05-26 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0002_auto_20180526_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desccription', models.CharField(max_length=50)),
                ('owners', models.ManyToManyField(related_name='owned_competencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='competencies',
            field=models.ManyToManyField(related_name='capable_engineers', to='cockpit.Competency'),
        ),
    ]
