# Generated by Django 2.0 on 2018-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0002_auto_20180213_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='reviewer_1st_line',
            field=models.ManyToManyField(blank=True, related_name='reviewed_action_plans_cww', to='cockpit.Engineer'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='reviewer_2nd_line',
            field=models.ManyToManyField(blank=True, related_name='reviewed_action_plans_lts', to='cockpit.Engineer'),
        ),
    ]
