# Generated by Django 2.0 on 2018-05-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0003_auto_20180213_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.CharField(blank=True, max_length=10, null=True)),
                ('high_priority', models.NullBooleanField(default=False)),
                ('status', models.CharField(blank=True, default='todo', max_length=30, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cockpit.Engineer')),
                ('owner', models.ManyToManyField(related_name='ownednotifications', to='cockpit.Engineer')),
            ],
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='reviewer_1st_line',
            field=models.ManyToManyField(blank=True, related_name='reviewed_action_plans_1st', to='cockpit.Engineer'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='reviewer_2nd_line',
            field=models.ManyToManyField(blank=True, related_name='reviewed_action_plans_2nd', to='cockpit.Engineer'),
        ),
        migrations.AddField(
            model_name='servicenotification',
            name='related_action_plan',
            field=models.ManyToManyField(blank=True, null=True, to='cockpit.ActionPlan'),
        ),
        migrations.AddField(
            model_name='servicenotification',
            name='related_task',
            field=models.ManyToManyField(blank=True, null=True, to='cockpit.Task'),
        ),
    ]
