# Generated by Django 2.0 on 2018-05-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0003_auto_20180526_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competency',
            old_name='desccription',
            new_name='description',
        ),
    ]
