# Generated by Django 2.0 on 2018-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0004_auto_20180526_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
